version: '2'
services:
  mock:
    build: ./query-services/mock
    ports:
     - "5000:5000"
    volumes:
     - .:/code
  language:
    build: ./query-services/language
    ports:
     - "5001:5001"
    volumes:
     - .:/code
  clarity-seed:
    build: ./clarity-seed/
    ports:
     - "4200:4200"
